# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zeenoc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for zeenoc
	pod 'Firebase/Firestore'
	#pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'GoogleDataTransport', '5.0.0'
	pod 'Charts'
	pod 'TinyConstraints'

  target 'zeenocTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'zeenocUITests' do
    # Pods for testing
  end

end
